version: '3'
services:
  app:
    # 실행 시킬 서버 코드, 다른 이름으로 지정해도 된다.
    build :
      # 빌드 명령을 실행할 디렉터리 경로
      context: .
      # 도커 이미지를 빌드하는데 사용할 도커 파일
      dockerfile: ./Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/jpastander
      SPRING_DATASOURCE_USERNAME: woojin
      SPRING_DATASOURCE_PASSWORD: 1234
    restart: always
    links:
    - mariadb:mariadb
    ports:
      - 8080:8080
    depends_on:
      # 의존 관계 설정
      - mariadb

  mariadb:
    # 'database'서비스에서 참조할 이미지
    image: mariadb
    ports:
      - 3306:3306
    restart: always
    environment:
      # 환경 설정에 필요한 설정들. server코드와 싱크를 맞추어야 한다.
      MARIADB_DATABASE : jpastander
      MARIADB_ROOT_PASSWORD : 1234
      MARIADB_USER: woojin
      MARIADB_PASSWORD: 1234