spring:
  datasource:
    url: jdbc:mariadb://3.38.33.154:3306/jpastander
    username: woojin
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false
  boot:
    admin:
      mail:
        from: ${spring.mail.username}
  mail:
    host: smtp.naver.com
    port: 465
    username: woojintestid@naver.com
    password: "!@woojintest"
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    session:
      timeout: 1800

file:
  dir: /usr/


